# Importing Libraties

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

*Loading the Dataset*

In [3]:
file_path = "../data/raw/MTA_Staten_Island_Railway_On-Time_Performance.xlsx"

df = pd.read_excel(file_path)

df.head()

,Month,Day Time,Delayed Trains,On-Time Trips,On-Time Performance,Delayed Trains (With Boat),On-Time Trips (With Boat),On-Time Performance (With Boat),Scheduled Trips,Incomplete Trips,Trip Complete Percentage
0,2006-01-01,Weekday,83,2621,0.969,124,2580,0.954,2704,NaN,NaN
1,2006-01-01,AM Rush,21,672,0.970,24,669,0.965,693,NaN,NaN
2,2006-01-01,PM Rush,10,830,0.988,34,806,0.960,840,NaN,NaN
3,2006-01-01,Weekend,96,722,0.883,103,715,0.874,818,NaN,NaN
4,2006-01-01,7-Day,179,3343,0.949,227,3295,0.936,3522,10.0,99.7%

In [4]:
df.shape

(1205, 11)

In [5]:
df.columns

Index(['Month', 'Day Time', 'Delayed Trains', 'On-Time Trips',
       'On-Time Performance', 'Delayed Trains (With Boat)',
       'On-Time Trips (With Boat)', 'On-Time Performance (With Boat)',
       'Scheduled Trips', 'Incomplete Trips', 'Trip Complete Percentage'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Month                            1205 non-null   datetime64[ns]
 1   Day Time                         1205 non-null   object
 2   Delayed Trains                   1205 non-null   int64
 3   On-Time Trips                    1205 non-null   int64
 4   On-Time Performance              1205 non-null   float64
 5   Delayed Trains (With Boat)       1205 non-null   int64
 6   On-Time Trips (With Boat)        1205 non-null   int64
 7   On-Time Performance (With Boat)  1205 non-null   float64
 8   Scheduled Trips                  1205 non-null   int64
 9   Incomplete Trips                 241 non-null    float64
 10  Trip Complete Percentage         241 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(5), object(2)
memory usage: 103.7+ KB

In [7]:
df.isnull().sum()

Month                                0
Day Time                             0
Delayed Trains                       0
On-Time Trips                        0
On-Time Performance                  0
Delayed Trains (With Boat)           0
On-Time Trips (With Boat)            0
On-Time Performance (With Boat)      0
Scheduled Trips                      0
Incomplete Trips                   964
Trip Complete Percentage           964
dtype: int64

In [8]:
df.head(10)

,Month,Day Time,Delayed Trains,On-Time Trips,On-Time Performance,Delayed Trains (With Boat),On-Time Trips (With Boat),On-Time Performance (With Boat),Scheduled Trips,Incomplete Trips,Trip Complete Percentage
0,2006-01-01,Weekday,83,2621,0.969,124,2580,0.954,2704,NaN,NaN
1,2006-01-01,AM Rush,21,672,0.970,24,669,0.965,693,NaN,NaN
2,2006-01-01,PM Rush,10,830,0.988,34,806,0.960,840,NaN,NaN
3,2006-01-01,Weekend,96,722,0.883,103,715,0.874,818,NaN,NaN
4,2006-01-01,7-Day,179,3343,0.949,227,3295,0.936,3522,10.0,99.7%
5,2006-02-01,Weekday,37,2410,0.985,50,2397,0.980,2447,NaN,NaN
6,2006-02-01,AM Rush,24,603,0.962,25,602,0.960,627,NaN,NaN
7,2006-02-01,PM Rush,8,790,0.990,16,782,0.980,798,NaN,NaN
8,2006-02-01,Weekend,14,723,0.981,15,722,0.980,737,NaN,NaN
9,2006-02-01,7-Day,51,3133,0.984,65,3119,0.980,3184,2.0,99.9%

# ==============================
# DATA CLEANING
# ==============================

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Month                               0.0
Day Time                            0.0
Delayed Trains                      0.0
On-Time Trips                       0.0
On-Time Performance                 0.0
Delayed Trains (With Boat)          0.0
On-Time Trips (With Boat)           0.0
On-Time Performance (With Boat)     0.0
Scheduled Trips                     0.0
Incomplete Trips                   80.0
Trip Complete Percentage           80.0
dtype: float64

In [11]:
df[df['Incomplete Trips'].isnull()].head()

,Month,Day Time,Delayed Trains,On-Time Trips,On-Time Performance,Delayed Trains (With Boat),On-Time Trips (With Boat),On-Time Performance (With Boat),Scheduled Trips,Incomplete Trips,Trip Complete Percentage
0,2006-01-01,Weekday,83,2621,0.969,124,2580,0.954,2704,NaN,NaN
1,2006-01-01,AM Rush,21,672,0.970,24,669,0.965,693,NaN,NaN
2,2006-01-01,PM Rush,10,830,0.988,34,806,0.960,840,NaN,NaN
3,2006-01-01,Weekend,96,722,0.883,103,715,0.874,818,NaN,NaN
5,2006-02-01,Weekday,37,2410,0.985,50,2397,0.980,2447,NaN,NaN

In [12]:
df[df['Trip Complete Percentage'].isnull()].head()

,Month,Day Time,Delayed Trains,On-Time Trips,On-Time Performance,Delayed Trains (With Boat),On-Time Trips (With Boat),On-Time Performance (With Boat),Scheduled Trips,Incomplete Trips,Trip Complete Percentage
0,2006-01-01,Weekday,83,2621,0.969,124,2580,0.954,2704,NaN,NaN
1,2006-01-01,AM Rush,21,672,0.970,24,669,0.965,693,NaN,NaN
2,2006-01-01,PM Rush,10,830,0.988,34,806,0.960,840,NaN,NaN
3,2006-01-01,Weekend,96,722,0.883,103,715,0.874,818,NaN,NaN
5,2006-02-01,Weekday,37,2410,0.985,50,2397,0.980,2447,NaN,NaN

In [13]:
df['Year'] = df['Month'].dt.year
df['Month_Number'] = df['Month'].dt.month
df['Month_Name'] = df['Month'].dt.month_name()

In [14]:
df.head()

,Month,Day Time,Delayed Trains,On-Time Trips,On-Time Performance,Delayed Trains (With Boat),On-Time Trips (With Boat),On-Time Performance (With Boat),Scheduled Trips,Incomplete Trips,Trip Complete Percentage,Year,Month_Number,Month_Name
0,2006-01-01,Weekday,83,2621,0.969,124,2580,0.954,2704,NaN,NaN,2006,1,January
1,2006-01-01,AM Rush,21,672,0.970,24,669,0.965,693,NaN,NaN,2006,1,January
2,2006-01-01,PM Rush,10,830,0.988,34,806,0.960,840,NaN,NaN,2006,1,January
3,2006-01-01,Weekend,96,722,0.883,103,715,0.874,818,NaN,NaN,2006,1,January
4,2006-01-01,7-Day,179,3343,0.949,227,3295,0.936,3522,10.0,99.7%,2006,1,January

In [15]:
df['Day Time'].unique()

array(['Weekday', 'AM Rush', 'PM Rush', 'Weekend', '7-Day'], dtype=object)

In [16]:
df['Trip Complete Percentage'].unique()

array([nan, '99.7%', '99.9%', '100.0%', '99.0%', '98.7%', '98.1%',
       '99.2%', '98.9%', '99.4%', '99.5%', '99.8%', '99.6%', '98.3%',
       '98.2%', '99.1%', '93.9%', '97.5%', '99.3%', '98.8%', '98.4%',
       '96.9%', '98.6%'], dtype=object)

In [17]:
df['Trip Complete Percentage'] = (
    df['Trip Complete Percentage']
    .astype(str)
    .str.replace('%', '', regex=False)
)

df['Trip Complete Percentage'] = pd.to_numeric(
    df['Trip Complete Percentage'],
    errors='coerce'
)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Month                            1205 non-null   datetime64[ns]
 1   Day Time                         1205 non-null   object
 2   Delayed Trains                   1205 non-null   int64
 3   On-Time Trips                    1205 non-null   int64
 4   On-Time Performance              1205 non-null   float64
 5   Delayed Trains (With Boat)       1205 non-null   int64
 6   On-Time Trips (With Boat)        1205 non-null   int64
 7   On-Time Performance (With Boat)  1205 non-null   float64
 8   Scheduled Trips                  1205 non-null   int64
 9   Incomplete Trips                 241 non-null    float64
 10  Trip Complete Percentage         241 non-null    float64
 11  Year                             1205 non-null   int32
 12  Month_Number                     1205 non-null   int32
 13  Month_Name                       1205 non-null   object
dtypes: datetime64[ns](1), float64(4), int32(2), int64(5), object(2)
memory usage: 122.5+ KB

In [19]:
df.to_csv('../data/raw/cleaned_staten_island_otp.csv', index=False)